= 设计模式
:toc:
:hardbreaks-option:

[.text-right]
🧐ME: 什么是设计模式？它们都解决了什么问题？

🙂BING: 23种设计模式是前辈们对代码开发经验的总结，是解决特定问题的一系列套路1。它们可以分为三大类：创建型、结构型和行为型。

创建型模式提供了一种在创建对象的同时隐藏创建逻辑的方式，而不是使用 new 运算符直接实例化对象。这使得程序在判断针对某个给定实例需要创建哪些对象时更加灵活。
结构型模式主要用于处理类或对象的组合。在这些模式中，一个类的创建依赖于另一个类的接口。
行为型模式主要用于描述类或对象之间如何交互以及分配职责。

下面是 23 种设计模式分别解决的问题和解决方案：

.创建型
* 单例模式：保证一个类仅有一个实例，并提供一个访问它的全局访问点。
* 工厂方法模式：定义一个用于创建对象的接口，让子类决定实例化哪一个类。工厂方法使一个类的实例化延迟到其子类。
* 抽象工厂模式：提供一个创建一系列相关或相互依赖对象的接口，而无需指定它们具体的类。
* 建造者模式：将一个复杂对象的构建与它的表示分离，使得同样的构建过程可以创建不同的表示。
* 原型模式：用原型实例指定创建对象的种类，并且通过拷贝这些原型创建新的对象。

.结构型
* 适配器模式：将一个类的接口转换成客户希望的另外一个接口。适配器模式使得原本由于接口不兼容而不能一起工作的那些类可以一起工作。适配器模式可以分为类适配器和对象适配器两种，前者是通过多重继承实现，后者是通过组合实现。
* 桥接模式：将抽象部分与它的实现部分分离，使它们都可以独立地变化。
* 组合模式：将对象组合成树形结构以表示“部分-整体”的层次结构。组合模式使得用户对单个对象和组合对象的使用具有一致性。
* 装饰模式：动态地给一个对象添加一些额外的职责。就增加功能来说，装饰模式比生成子类更为灵活。
* 外观模式：为子系统中的一组接口提供一个一致的界面，外观模式定义了一个高层接口，这个接口使得这一子系统更加容易使用。
* 享元模式：运用共享技术有效地支持大量细粒度的对象。
* 代理模式：为其他对象提供一种代理以控制对这个对象的访问。
.行为型
* 模板方法模式：定义一个操作中的算法的骨架，而将一些步骤延迟到子类中。模板方法使得子类可以不改变一个算法的结构即可重定义该算法的某些特定步骤。
* 命令模式：将一个请求封装为一个对象，从而使你可用不同的请求对客户进行参数化；对请求排队或记录请求日志，以及支持可撤销的操作。
* 迭代器模式：提供一种方法顺序访问一个聚合对象中各个元素,而又不需暴露该对象的内部表示。
* 观察者模式：定义了一种一对多的依赖关系，让多个观察者对象同时监听某一个主题对象。这个主题对象在状态发生变化时通知它的所有观察者对象。
* 状态模式：允许一个对象在其内部状态改变时改变它的行为。对象看起来似乎修改了它的类。
* 策略模式：定义一系列的算法,把它们一个个封装起来,并且使它们可相互替换。本模式使得算法可独立于使用它的客户而变化。
* 责任链模式：为解除请求的发送者和接收者之间耦合，而使多个对象都有机会处理这个请求。将这些对象连成一条链，并沿着这条链传递该请求，直到有一个对象处理它为止。
* 中介者模式：用一个中介对象来封装一系列的对象交互。中介者使各对象不需要显式地相互引用，从而使其耦合松散，而且可以独立地改变它们之间的交互。
* 解释器模式：给定一个语言，定义它的文法的一种表示，并定义一个解释器，这个解释器使用该表示来解释语言中的句子。
* 访问者模式：表示一个作用于某对象结构中的各元素的操作。它使你可以在不改变各元素的类的前提下，定义作用于这些元素的新操作。
* 备忘录模式：在不破坏封装性的前提下，捕获一个对象的内部状态，并在该对象之外保存这个状态。这样以后就可将该对象恢复到原先保存的状态。
* 空对象模式：在空对象模式中，一个空对象取代 NULL 对象实例的检查。Null 对象不是检查空值，而是反应一个不做任何动作的关系。这样的 Null 对象也可以在数据不可用的时候提供默认的行为。
* 备忘录模式：在不破坏封装性的前提下，捕获一个对象的内部状态，并在该对象之外保存这个状态。这样以后就可将该对象恢复到原先保存的状态。
* 空对象模式：在空对象模式中，一个空对象取代 NULL 对象实例的检查。Null 对象不是检查空值，而是反应一个不做任何动作的关系。这样的 Null 对象也可以在数据不可用的时候提供默认的行为。
* 等待模式：等待模式是一种行为型设计模式，它允许一个对象暂停执行，直到它满足了一个预定义的条件。等待模式可以用于实现同步、异步和并发编程中的协调机制。
* 服务定位器模式：服务定位器模式是一种创建型设计模式，它提供了一种通过 JNDI 查找服务的统一接口，以减少客户端对服务对象的依赖。服务定位器模式可以用于实现依赖注入和控制反转。

== 创建型模式
=== 单例模式
[.text-right]
🧐ME: 什么是单例模式？都有哪些实现方式，请给出java代码以说明。

🙂BING:

.单例模式有以下几种实现方式
* 懒汉式：在第一次调用时才创建对象，需要考虑线程安全问题。
* 饿汉式：在类加载时就创建对象，不需要考虑线程安全问题，但可能造成资源浪费。
* 双重检查锁：在懒汉式的基础上加入双重检查锁机制，保证线程安全和性能。
* 静态内部类：利用静态内部类的特性，在第一次使用时才加载内部类，实现延迟加载和线程安全。
* 枚举：利用枚举类型的特性，在枚举中定义一个实例，实现简洁和序列化支持。

.每种单例模式的示例代码
[source,java]
----
// 懒汉式
public class Singleton {
    private static Singleton instance;
    private Singleton() {}
    public static synchronized Singleton getInstance() {
        if (instance == null) {
            instance = new Singleton();
        }
        return instance;
    }
}

// 饿汉式
public class Singleton {
    private static final Singleton instance = new Singleton();
    private Singleton() {}
    public static Singleton getInstance() {
        return instance;
    }
}

// 双重检查锁
public class Singleton {
    private volatile static Singleton instance;
    private Singleton() {}
    public static Singleton getInstance() {
        if (instance == null) {
            synchronized (Singleton.class) {
                if (instance == null) {
                    instance = new Singleton();
                }
            }
        }
        return instance;
    }
}

// 静态内部类
public class Singleton {
    private static class Holder {
        private static final Singleton INSTANCE = new Singleton();
    }
    private Singleton() {}
    public static final Singleton getInstance() {
        return Holder.INSTANCE;
    }
}

// 枚举
public enum Singleton {
    INSTANCE;
}
----

.每种单例模式的优缺点：
|===
| 单例模式 | 优点 | 缺点

| 懒汉式 | 实现了延迟加载，节省了内存资源 | 需要同步锁，影响了性能

| 饿汉式 | 简单易实现，不需要同步锁，避免了线程安全问题 | 没有实现延迟加载，可能造成资源浪费

| 双重检查锁 | 实现了延迟加载和线程安全，性能较高 | 代码复杂度较高，需要使用volatile关键字防止指令重排

| 静态内部类 | 实现了延迟加载和线程安全，代码简洁 | 不能防止反射和序列化破坏单例

| 枚举 | 实现最简单，自动支持序列化机制，防止反射和序列化破坏单例 | 不能继承其他类 
|===


=== 工厂方法模式

[.text-right]
🧐ME: 什么是工厂方法模式？请给出java代码以说明。

🙂BING:

* 工厂方法模式是一种创建型设计模式，它定义了一个创建产品对象的工厂接口，将实际创建工作推迟到子类当中。这样做的目的是将产品类的实例化操作延迟到工厂子类中完成，即通过工厂子类来确定究竟应该实例化哪一个具体产品类。
* 工厂方法模式解决了简单工厂模式中的缺点，即当需要增加新的产品时，不需要修改原有的工厂类代码，而只需增加一个具体的产品类和对应的具体工厂类。这样就遵循了开闭原则，即对扩展开放，对修改关闭。

下面是一个用java代码说明的例子：
假设有一个抽象产品接口Shape和两个具体产品类Circle和Rectangle，以及一个抽象工厂接口ShapeFactory和两个具体工厂类CircleFactory和RectangleFactory。
代码如下：
[source,java]
----
// 抽象产品接口
public interface Shape {
    void draw();
}

// 具体产品类
public class Circle implements Shape {
    @Override
    public void draw() {
        System.out.println("Draw a circle.");
    }
}

public class Rectangle implements Shape {
    @Override
    public void draw() {
        System.out.println("Draw a rectangle.");
    }
}

// 抽象工厂接口
public interface ShapeFactory {
    Shape createShape();
}

// 具体工厂类
public class CircleFactory implements ShapeFactory {
    @Override
    public Shape createShape() {
        return new Circle();
    }
}

public class RectangleFactory implements ShapeFactory {
    @Override
    public Shape createShape() {
        return new Rectangle();
    }
}
----

使用时，只需根据需要创建相应的具体工厂对象，并调用其createShape()方法即可得到相应的具体产品对象。例如：
[source,java]
----
// 创建圆形工厂对象
ShapeFactory circleFactory = new CircleFactory();
// 通过圆形工厂对象创建圆形对象
Shape circle = circleFactory.createShape();
// 调用圆形对象的draw()方法
circle.draw();

// 创建矩形工厂对象
ShapeFactory rectangleFactory = new RectangleFactory();
// 通过矩形工厂对象创建矩形对象
Shape rectangle = rectangleFactory.createShape();
// 调用矩形对象的draw()方法
rectangle.draw();
----

输出结果为：
Draw a circle.
Draw a rectangle.

==== 简单工厂模式？
[.text-right]
🧐ME: 简单工厂模式是23种设计模式种的一种吗？

🙂BING: 不是的。简单工厂模式并不是23种设计模式中的一种，它只是一种编程习惯，也叫做静态工厂方法。23种设计模式中的工厂模式包括工厂方法模式和抽象工厂模式。它不符合开闭原则1，即对扩展开放，对修改关闭。简单工厂模式在增加新的产品时需要修改工厂类的代码，违反了开闭原则。而真正的设计模式应该是能够在不修改原有代码的基础上增加新的功能或者改变行为。

[.text-right]
🧐ME: 简单工厂模式与工厂方法模式有什么区别？

🙂BING: 工厂方法模式和简单工厂模式的区别主要有以下几点：
* 简单工厂模式只有一个工厂类，根据传入的参数来创建不同的对象，而工厂方法模式有一个抽象的工厂接口或类，每个子类对应一个具体的对象。
* 简单工厂模式违反了开闭原则，当需要增加新的对象时，需要修改工厂类的代码，而工厂方法模式符合开闭原则，只需要增加新的子类和对应的对象即可。
* 简单工厂模式将创建对象的逻辑封装在工厂类中，客户端只需要传入参数即可，而工厂方法模式将创建对象的逻辑转移到了客户端中，客户端需要选择合适的子类来创建对象。

[.text-right]
🧐ME: 请给我一个简单工厂模式和工厂方法模式的代码对比。

🙂BING: 假设我们有一个抽象的产品类Product，和两个具体的产品类ProductA和ProductB。

[source,java]
----
// 抽象产品类
public abstract class Product {
    public abstract void show();
}

// 具体产品类A
public class ProductA extends Product {
    @Override
    public void show() {
        System.out.println("This is product A.");
    }
}

// 具体产品类B
public class ProductB extends Product {
    @Override
    public void show() {
        System.out.println("This is product B.");
    }
}

简单工厂模式的代码如下：
// 简单工厂类
public class SimpleFactory {
    // 根据参数创建不同的产品对象并返回
    public static Product createProduct(String type) {
        if (type.equals("A")) {
            return new ProductA();
        } else if (type.equals("B")) {
            return new ProductB();
        } else {
            return null;
        }
    }
}

// 客户端类
public class Client {
    public static void main(String[] args) {
        // 通过简单工厂创建产品对象并使用
        Product product = SimpleFactory.createProduct("A");
        product.show();
    }
}
工厂方法模式的代码如下：
// 抽象工厂接口或类
public interface Factory {
    // 每个子类对应一个具体的产品对象并返回
    public Product createProduct();
}

// 具体工厂类A，创建并返回具体产品对象A
public class FactoryA implements Factory {
    @Override
    public Product createProduct() {
        return new ProductA();
    }
}

// 具体工厂类B，创建并返回具体产品对象B
public class FactoryB implements Factory {
    @Override
    public Product createProduct() {
        return new ProductB();
    }
}

// 客户端类，与简单工厂模式不同，需要选择合适的子类来创建对象。
public class Client2 {

    public static void main(String[] args) {

        Factory factory = new FactoryA(); // 选择合适的子类来创建对象
        
        Product product = factory.createProduct(); // 通过抽象接口或父类调用方法
        
        product.show(); // 使用对象
        
    }
}
----


从上面的代码对比可以看出：
* 简单工厂模式只有一个静态方法createProduct来根据参数创建不同的对象，而工厂方法模式有一个抽象接口或父类Factory和多个子类FactoryA和FactoryB来分别创建对应的对象。
* 简单工厂模式在增加新的对象时需要修改createProduct方法中的判断逻辑，而工厂方法模式在增加新的对象时只需要增加新的子类即可。
* 简单工厂模式在客户端只需要传入参数即可获取对象，而工厂方法模式在客户端需要先选择合适的子类然后通过抽象接口或父类调用方法获取对象。

===	抽象工厂模式

[.text-right]
🧐ME: 什么是抽象工厂模式，请用java代码说明。

🙂BING: 抽象工厂模式是一种创建型设计模式，它能创建一系列相关的对象，而无需指定其具体类。抽象工厂定义了用于创建不同产品的接口，但将实际的创建工作留给了具体工厂类。例如，笔记本、手机、路由器等都是不同的产品，华为、苹果、联想等都是不同的工厂。
用java代码说明的话，可以参考以下示例：
[source,java]
----
// 抽象产品：按钮
interface Button {
    void paint();
}

// 具体产品：MacOS按钮
class MacOSButton implements Button {
    @Override
    public void paint() {
        System.out.println("你已经创建了MacOSButton.");
    }
}

// 具体产品：Windows按钮
class WindowsButton implements Button {
    @Override
    public void paint() {
        System.out.println("你已经创建了WindowsButton.");
    }
}

// 抽象产品：复选框
interface Checkbox {
    void paint();
}

// 具体产品：MacOS复选框
class MacOSCheckbox implements Checkbox {
    @Override
    public void paint() {
        System.out.println("你已经创建了MacOSCheckbox.");
    }
}

// 具体产品：Windows复选框
class WindowsCheckbox implements Checkbox {
    @Override
    public void paint() {
        System.out.println("你已经创建了WindowsCheckbox.");
    }
}

// 抽象工厂：GUI工厂
interface GUIFactory {
    Button createButton();
    Checkbox createCheckbox();
}

// 具体工厂：MacOS GUI工厂
class MacOSFactory implements GUIFactory {

    @Override
    public Button createButton() {
        return new MacOSButton();
    }

    @Override
    public Checkbox createCheckbox() {
        return new MacOSCheckbox();
    }
}

// 具体工厂：Windows GUI工厂
class WindowsFactory implements GUIFactory {

   @Override
   public Button createButton() {
       return new WindowsButton();
   }

   @Override
   public Checkbox createCheckbox() {
       return new WindowsCheckbox();
   }
}
----

[.text-right]
🧐ME: 这个模式有什么优缺点？

🙂BING: 
抽象工厂模式的优点有：
抽象工厂模式隔离了具体类的生产，使得客户并不需要知道什么被创建。
当一个产品族中的多个对象被设计成一起工作时，它能保证客户端始终只使用同一个产品族中的对象。
增加新的具体工厂和产品族很方便，无须修改已有系统，符合“开闭原则”。

抽象工厂模式的缺点有：
抽象工厂模式的扩展性不好。如果要增加一个新的产品，就要修改抽象工厂和所有的具体工厂，违反了“开闭原则”。
抽象工厂模式增加了系统的抽象性和理解难度。如果产品族过多或者层次过深，会导致类数目急剧增加，增加了系统复杂度。

[.text-right]
🧐ME: 抽象工厂模式和工厂方法模式有什么区别？

🙂BING: 
抽象工厂模式和工厂方法模式的区别主要有以下几点：
工厂方法模式只有一个抽象产品类，具体工厂类只能创建一个具体产品类的实例；抽象工厂模式有多个抽象产品类，具体工厂类能创建多个具体产品类的实例。
工厂方法模式针对的是一个产品等级结构，即同一种类型的产品；抽象工厂模式针对的是多个产品等级结构，即不同类型的产品。
工厂方法模式通过让子类决定该创建的对象是什么，来达到将对象创建的过程封装的目的；抽象工厂模式提供一个接口，用来创建相关或依赖对象的家族，而不需要明确指定具体类。

[.text-right]
🧐ME: 不够清楚，能再详细解释一下吗

🙂BING: 好的，我尽量再详细解释一下。
抽象工厂模式和工厂方法模式都是创建型模式，用来封装对象的创建过程，但是它们有不同的应用场景和实现方式。为了方便理解，我给你举一个例子：
假设有一个富商，在深圳开了三个手机厂，分别代工苹果手机，三星手机，华为手机。每个手机厂都有自己的生产线，可以生产不同型号的手机。如果我们要用代码来描述这个场景，我们可以这样设计：

工厂方法模式：我们定义一个抽象类PhoneFactory，它有一个抽象方法createPhone()，让子类实现这个方法来创建具体的手机对象。然后我们定义三个具体的工厂类AppleFactory、SamsungFactory、HuaweiFactory，它们分别继承自PhoneFactory，并重写createPhone()方法来创建苹果、三星、华为的具体手机对象。这样我们就可以根据不同的工厂对象来创建不同品牌的手机对象。

抽象工厂模式：我们定义一个接口AbstractFactory，它有多个抽象方法createApple()、createSamsung()、createHuawei()等，用来创建不同品牌的手机对象。然后我们定义三个具体的工厂类Shenzhen1Factory、Shenzhen2Factory、Shenzhen3Factory，它们分别实现AbstractFactory接口，并实现各自的抽象方法来创建具体的手机对象。这样我们就可以根据不同的工厂对象来创建多种品牌和型号的手机对象。
从上面的例子可以看出：
工厂方法模式只能创建一种类型（品牌）的产品（手机），而抽象工厂模式可以创建多种类型（品牌）和等级（型号）的产品（手机）。
工厂方法模式是通过继承抽象类并重写抽象方法来实现具体产品（手机）的创建；而抽象工厂模式是通过实现接口并实现多个抽象方法来实现多种产品（手机）的创建。
工厂方法模式适合于产品等级结构单一且稳定不变化时使用；而抽象工厂模式适合于产品等级结构复杂且经常变化时使用。
希望这样能让你更清楚地理解两者之间的区别。

[.text-right]
🧐ME: 你能用字符拼接出一个图片，用于展示抽象工厂的类图吗？

🙂BING: 
[source,txt]
----
+------------------+                  +-----------------+
|  AbstractFactory |<-----------------|    Client       |
+------------------+                  +-----------------+
| +createProductA()|                  | -factory        |
| +createProductB()|                  | +Client(factory)|
+------------------+                  | +doSomething()  |
         ^    ^                       +-----------------+
         |    |
         |    +---------------+                      +--------------+   +--------------+
         |                    |                      |  ProductA    |   |  ProductB    |
+-----------------+  +-----------------+             +--------------+   +--------------+
|ConcreteFactory1 |  |ConcreteFactory2 |             |-name             |-name
+-----------------+  +-----------------+             |-price            |-price
|+createProductA()|  |+createProductA()|
|+createProductB()|  |+createProductB()|
----

===	建造者模式

[.text-right]
🧐ME: 什么是建造者模式？我们为什么要使用建造者模式？请用java代码说明。

🙂BING: 建造者模式是一种创建型模式，它将一个复杂对象的构建与它的表示分离，使得同样的构建过程可以创建不同的表示。它允许用户只通过复杂对象的类型和内容就可以构建它们，而不需要用户知道内部的具体细节。
用java代码说明的话，可以参考以下示例：
[source,java]
----
//产品类
class Meal {
    private String burger;
    private String cola;
    private String fries;

    public void setBurger(String burger) {
        this.burger = burger;
    }

    public void setCola(String cola) {
        this.cola = cola;
    }

    public void setFries(String fries) {
        this.fries = fries;
    }

    public void show() {
        //显示套餐内容
        System.out.println("burger: " + burger);
        System.out.println("cola: " + cola);
        System.out.println("fries: " + fries);
    }
}

//抽象建造者
abstract class MealBuilder {
    //创建产品对象
    protected Meal meal = new Meal();

    public abstract void buildBurger();

    public abstract void buildCola();

    public abstract void buildFries();

    //返回产品对象
    public Meal getResult() {
        return meal;
    }
}

//具体建造者1
class AMealBuilder extends MealBuilder {

    @Override
    public void buildBurger() {
        meal.setBurger("牛肉汉堡");
    }

    @Override
    public void buildCola() {
        meal.setCola("可口可乐");
    }

    @Override
    public void buildFries() {
        meal.setFries("大份薯条");
    }
}

//具体建造者2
class BMealBuilder extends MealBuilder {

    @Override
    public void buildBurger() {
        meal.setBurger("鸡肉汉堡");
    }

    @Override
    public void buildCola() {
        meal.setCola("百事可乐");
    }

    @Override
    public void buildFries() {
        meal.setFries("中份薯条");
    }
}

//指挥者类（服务员）
//指挥者类的作用是封装建造者的使用，让客户端不需要直接操作建造者对象，而只需要指定想要的套餐类型，
//由指挥者类来负责调用建造者的方法来组装产品。这样可以降低客户端和建造者之间的耦合度，也可以方便地更换不同的建造者或修改组装顺序。
class Waiter {

    private MealBuilder builder;

    //设置当前使用的建造者对象（可用于切换不同的建造者）
    public Waiter(MealBuilder builder) {
        this.builder = builder;
    }

    //构建产品（可用于指定不同的组装顺序或步骤）
    public Meal serveMeal() {
        builder.buildBurger();
        builder.buildCola();
        builder.buildFries();
        return builder.getResult();
    }

}

//客户端测试代码

public class Client {

    public static void main(String[] args) {

        MealBuilder aMealBuilder = new AMealBuilder();
        Waiter waiter1 = new Waiter(aMealBuilder);
        Meal aMeal = waiter1.serveMeal();
        aMeal.show();

        MealBuilder bMealBuilder = new BMealBuilder();
        Waiter waiter2 = new Waiter(bMealBuilder);
        Meal bMeal = waiter2.serveMeal();
        bMeal.show();

    }
}
----

输出结果为：
----
burger: 牛肉汉堡
cola: 可口可乐
fries: 大份薯条
burger: 鸡肉汉堡
cola: 百事可乐
fries: 中份薯条
----

[.text-right]
🧐ME: 建造者模式和工厂模式有什么区别？什么时候应该使用建造者模式而不是工厂模式？

🙂BING: 
建造者模式和工厂模式的区别是：工厂模式注重的是整体对象的创建方式，建造者模式注重的是部件构建的过程，意在通过一步一步地精确构造创建出一个复杂的对象。工厂模式是一个对象创建的粗线条应用，建造者模式则是通过细线条勾勒出一个复杂对象，关注的是产品组成部分的创建过程。
一般来说，当你需要创建的对象包含多个组件，而且这些组件的创建过程需要分步进行，并且可以有不同的组合方式时，你可以使用建造者模式。建造者模式可以让你把对象的构建和表示分离，使得同样的构建过程可以创建出不同的表示。而工厂模式更适合于产品对象较少，或者产品的创建方式比较简单和固定的情况。

[.text-right]
🧐ME: 你能给我一个在jdk的源码中使用建造者模式的例子吗？

🙂BING:
一个在jdk源码中使用建造者模式的例子是StringBuilder类。它是一个抽象建造者的子类，实现了Appendable接口的多个append方法，用于构建字符串对象。它还提供了一个toString方法，用于返回最终创建的字符串对象。

[.text-right]
🧐ME: 你能用字符拼接出一个图片，用于展示建造者模式的类图吗？
🙂BING:

[source,text]
----
+----------------+     +----------------+
|   Director     |     | <<interface>>  |
|+Builder builder|o----|   Builder      |
| +construct()   |     +----------------+
+----------------+     | +buildPart()   |
                       +----------------+
                                ^
                                -
                                |
+----------------+     +-----------------+
|    Product     |<----|  ConcreteBuilder|
|                |     | +buildPart()    |
+----------------+     | +getResult()    |
                       +-----------------+
----

=== 原型模式

原型模式是一种创建型设计模式，它允许您复制对象，甚至是复杂对象，而无需使代码依赖于它们所属的类。所有原型类都必须具有一个通用接口，以便在不知道对象所属的具体类的情况下也能够复制对象。原型对象可以生成自身的完整副本，因为相同类的对象可以相互访问对方的私有成员变量。

下面是一个简单的Java示例代码：

[source,java]
----
import java.util.Objects;

//这是一个抽象Shape类，它定义了一个克隆方法来创建当前形状对象的副本。这个方法将由子类实现。
public abstract class Shape {
    public int x;
    public int y;
    public String color;

    public Shape() {
    }

    public Shape(Shape target) {
        if (target != null) {
            this.x = target.x;
            this.y = target.y;
            this.color = target.color;
        }
    }

    public abstract Shape clone();

    @Override
    public boolean equals(Object object2) {
        if (!(object2 instanceof Shape)) return false;
        Shape shape2 = (Shape) object2;
        return shape2.x == x && shape2.y == y && Objects.equals(shape2.color, color);
    }
}
----

